### ISSUE TITLE
TS typings

### ISSUE THREAD

**Issue by Andarist** [staltz/callbag-subject#4]
I'm trying to implement TS types for this package, but it seems to be hard with currently provided types. Any ideas how to make it work?

[playground](https://www.typescriptlang.org/play/#src=declare%20function%20pipe%3CT1%2C%20T2%3E(first%3A%20T1%2C%20second%3A%20(a%3A%20T1)%20%3D%3E%20T2)%3A%20T2%0D%0Adeclare%20function%20pipe%3CT1%2C%20T2%2C%20T3%3E(%0D%0A%20%20first%3A%20T1%2C%0D%0A%20%20second%3A%20(a%3A%20T1)%20%3D%3E%20T2%2C%0D%0A%20%20third%3A%20(a%3A%20T2)%20%3D%3E%20T3%2C%0D%0A)%3A%20T3%0D%0Adeclare%20function%20pipe%3CT1%2C%20T2%2C%20T3%2C%20T4%3E(%0D%0A%20%20first%3A%20T1%2C%0D%0A%20%20second%3A%20(a%3A%20T1)%20%3D%3E%20T2%2C%0D%0A%20%20third%3A%20(a%3A%20T2)%20%3D%3E%20T3%2C%0D%0A%20%20fourth%3A%20(a%3A%20T3)%20%3D%3E%20T4%2C%0D%0A)%3A%20T4%0D%0Adeclare%20function%20pipe%3CT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%3E(%0D%0A%20%20first%3A%20T1%2C%0D%0A%20%20second%3A%20(a%3A%20T1)%20%3D%3E%20T2%2C%0D%0A%20%20third%3A%20(a%3A%20T2)%20%3D%3E%20T3%2C%0D%0A%20%20fourth%3A%20(a%3A%20T3)%20%3D%3E%20T4%2C%0D%0A%20%20fifth%3A%20(a%3A%20T4)%20%3D%3E%20T5%2C%0D%0A)%3A%20T5%0D%0Adeclare%20function%20pipe%3CT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%2C%20T6%3E(%0D%0A%20%20first%3A%20T1%2C%0D%0A%20%20second%3A%20(a%3A%20T1)%20%3D%3E%20T2%2C%0D%0A%20%20third%3A%20(a%3A%20T2)%20%3D%3E%20T3%2C%0D%0A%20%20fourth%3A%20(a%3A%20T3)%20%3D%3E%20T4%2C%0D%0A%20%20fifth%3A%20(a%3A%20T4)%20%3D%3E%20T5%2C%0D%0A%20%20sixth%3A%20(a%3A%20T5)%20%3D%3E%20T6%2C%0D%0A)%3A%20T6%0D%0Adeclare%20function%20pipe%3CT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%2C%20T6%2C%20T7%3E(%0D%0A%20%20first%3A%20T1%2C%0D%0A%20%20second%3A%20(a%3A%20T1)%20%3D%3E%20T2%2C%0D%0A%20%20third%3A%20(a%3A%20T2)%20%3D%3E%20T3%2C%0D%0A%20%20fourth%3A%20(a%3A%20T3)%20%3D%3E%20T4%2C%0D%0A%20%20fifth%3A%20(a%3A%20T4)%20%3D%3E%20T5%2C%0D%0A%20%20sixth%3A%20(a%3A%20T5)%20%3D%3E%20T6%2C%0D%0A%20%20seventh%3A%20(a%3A%20T6)%20%3D%3E%20T7%2C%0D%0A)%3A%20T7%0D%0Adeclare%20function%20pipe%3CT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%2C%20T6%2C%20T7%2C%20T8%3E(%0D%0A%20%20first%3A%20T1%2C%0D%0A%20%20second%3A%20(a%3A%20T1)%20%3D%3E%20T2%2C%0D%0A%20%20third%3A%20(a%3A%20T2)%20%3D%3E%20T3%2C%0D%0A%20%20fourth%3A%20(a%3A%20T3)%20%3D%3E%20T4%2C%0D%0A%20%20fifth%3A%20(a%3A%20T4)%20%3D%3E%20T5%2C%0D%0A%20%20sixth%3A%20(a%3A%20T5)%20%3D%3E%20T6%2C%0D%0A%20%20seventh%3A%20(a%3A%20T6)%20%3D%3E%20T7%2C%0D%0A%20%20eigth%3A%20(a%3A%20T7)%20%3D%3E%20T8%2C%0D%0A)%3A%20T8%0D%0Adeclare%20function%20pipe%3CT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%2C%20T6%2C%20T7%2C%20T8%2C%20T9%3E(%0D%0A%20%20first%3A%20T1%2C%0D%0A%20%20second%3A%20(a%3A%20T1)%20%3D%3E%20T2%2C%0D%0A%20%20third%3A%20(a%3A%20T2)%20%3D%3E%20T3%2C%0D%0A%20%20fourth%3A%20(a%3A%20T3)%20%3D%3E%20T4%2C%0D%0A%20%20fifth%3A%20(a%3A%20T4)%20%3D%3E%20T5%2C%0D%0A%20%20sixth%3A%20(a%3A%20T5)%20%3D%3E%20T6%2C%0D%0A%20%20seventh%3A%20(a%3A%20T6)%20%3D%3E%20T7%2C%0D%0A%20%20eigth%3A%20(a%3A%20T7)%20%3D%3E%20T8%2C%0D%0A%20%20ninth%3A%20(a%3A%20T8)%20%3D%3E%20T9%2C%0D%0A)%3A%20T9%0D%0Adeclare%20function%20pipe%3CT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%2C%20T6%2C%20T7%2C%20T8%2C%20T9%2C%20T10%3E(%0D%0A%20%20first%3A%20T1%2C%0D%0A%20%20second%3A%20(a%3A%20T1)%20%3D%3E%20T2%2C%0D%0A%20%20third%3A%20(a%3A%20T2)%20%3D%3E%20T3%2C%0D%0A%20%20fourth%3A%20(a%3A%20T3)%20%3D%3E%20T4%2C%0D%0A%20%20fifth%3A%20(a%3A%20T4)%20%3D%3E%20T5%2C%0D%0A%20%20sixth%3A%20(a%3A%20T5)%20%3D%3E%20T6%2C%0D%0A%20%20seventh%3A%20(a%3A%20T6)%20%3D%3E%20T7%2C%0D%0A%20%20eigth%3A%20(a%3A%20T7)%20%3D%3E%20T8%2C%0D%0A%20%20ninth%3A%20(a%3A%20T8)%20%3D%3E%20T9%2C%0D%0A%20%20tenth%3A%20(a%3A%20T9)%20%3D%3E%20T10%2C%0D%0A)%3A%20T10%0D%0A%0D%0Aexport%20default%20pipe%0D%0A%0D%0Aexport%20type%20START%20%3D%200%3B%0D%0Aexport%20type%20DATA%20%3D%201%3B%0D%0Aexport%20type%20END%20%3D%202%3B%0D%0Aexport%20type%20RESERVED_3%20%3D%203%3B%0D%0Aexport%20type%20RESERVED_4%20%3D%204%3B%0D%0Aexport%20type%20RESERVED_5%20%3D%205%3B%0D%0Aexport%20type%20RESERVED_6%20%3D%206%3B%0D%0Aexport%20type%20RESERVED_7%20%3D%207%3B%0D%0Aexport%20type%20RESERVED_8%20%3D%208%3B%0D%0Aexport%20type%20RESERVED_9%20%3D%209%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20A%20Callbag%20dynamically%20receives%20input%20of%20type%20I%0D%0A%20*%20and%20dynamically%20delivers%20output%20of%20type%20O%0D%0A%20*%2F%0D%0Aexport%20type%20Callbag%3CI%2C%20O%3E%20%3D%20%7B%0D%0A%20%20(t%3A%20START%2C%20d%3A%20Callbag%3CO%2C%20I%3E)%3A%20void%3B%0D%0A%20%20(t%3A%20DATA%2C%20d%3A%20I)%3A%20void%3B%0D%0A%20%20(t%3A%20END%2C%20d%3F%3A%20any)%3A%20void%3B%0D%0A%7D%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20A%20source%20only%20delivers%20data%0D%0A%20*%2F%0D%0Aexport%20type%20Source%3CT%3E%20%3D%20Callbag%3Cvoid%2C%20T%3E%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20A%20sink%20only%20receives%20data%0D%0A%20*%2F%0D%0Aexport%20type%20Sink%3CT%3E%20%3D%20Callbag%3CT%2C%20void%3E%3B%0D%0A%0D%0Aexport%20type%20SourceFactory%3CT%3E%20%3D%20(...args%3A%20Array%3Cany%3E)%20%3D%3E%20Source%3CT%3E%3B%0D%0A%0D%0Aexport%20type%20SourceOperator%3CT%2C%20R%3E%20%3D%20(%0D%0A%20%20...args%3A%20Array%3Cany%3E%0D%0A)%20%3D%3E%20(source%3A%20Source%3CT%3E)%20%3D%3E%20Source%3CR%3E%3B%0D%0A%0D%0Adeclare%20function%20fromEvent%3CT%20extends%20keyof%20HTMLElementEventMap%3E(%0D%0A%20%20node%3A%20EventTarget%2C%0D%0A%20%20name%3A%20T%2C%0D%0A%20%20options%3F%3A%20boolean%20%7C%20AddEventListenerOptions%0D%0A)%3A%20Source%3CHTMLElementEventMap%5BT%5D%3E%3B%0D%0A%0D%0Adeclare%20function%20map%3CI%2C%20O%3E(fn%3A%20(input%3A%20I)%20%3D%3E%20O)%3A%20(source%3A%20Source%3CI%3E)%20%3D%3E%20Source%3CO%3E%3B%20%0D%0A%0D%0Adeclare%20function%20makeSubject%3CT%3E()%3A%20Callbag%3CT%2C%20T%3E%3B%0D%0A%0D%0Aconst%20s%20%3D%20makeSubject%3Cnumber%3E()%0D%0A%0D%0Apipe(%0D%0A%20%20%20%20s%2C%0D%0A%20%20%20%20map(ev%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%0D%0A%20%20%20%20%7D)%0D%0A)%0D%0A%0D%0A)

**Comment by zebulonj** [comment]
Ooh. I'm interested in this effort. May not have a chance to look at it today, but I'll circle back.

**Comment by Tangent128** [comment]
I think the problem there is actually in `map`'s typings; `map` declares that it expects a `Source`, which forces the talkback channel's type to be `void`.

If you change `map` to have a type parameter for the talkback, the example works:

```typescript
declare function map<I, O, TB>(fn: (input: I) => O): (source: Callbag<TB, I>) => Callbag<TB, O>;
```

**Comment by loreanvictor** [comment]
@Tangent128 's suggestion seems to work properly ([playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwAcsCQAeAFQEYAaecgJgD4AKRLGAZwwC46b4O4PMF7MovKgEp4AXkZ16kifQCwAKFCRYCFOmx5CxMlVoNTAZhbr4Sdlwk1rAoahHwxD6XIXUnGABbsbh4KXvLk5r5qSnTm6prQcEhomLj4RCQU-GaxpgAsVmo2bJw8fFE2gmDCouJ8YT5+gTDBdQwNERVIOMgwAbUS5h15UTHkefHgiTop+ulGWab0FvmmAKyFxXZlJk5VNe5tlB3LTUEDobLhkU6IPX3+FxHDXWyI-YcSeR1roxJrky0SV0qQMGWM2WWuToIzovzoADZNrZSg4uvtXE9jldGkV4AFzp9Lt5Ord7h8Qs8ceNXlh3o8ieMfuisAAPCltNYdBF-RGA6bJPRpQyZEw+aE0uGmHl0ADsyJK9nKexcrU81NOeIJLSeimpNzxd16HMGL1udJNMOZezZlvIXOpPJVADcQKg7QiOrLeeRZfztILQfNRZCVjD1tLTN66AAOBXbNEq6qYxnYkmamzatXE66vckMylDakjc30p7fam-G3sguc7nokCu921iSe6nepwgLAAcztso6MZ9Mf9wNmwvBi3FnXDUsRUdMg7oAE546jlXiMdmpBqulndR0DcV808iySS4aLS2rZWWTWng6SU6N423R6vV0u72r76B11UFhmyeGMOiXH0lxHGYhTBBYxRyadJXtSM5QXUxQL4AAGVclV2Z9ky3NNwgzfFmi3PUSUPbpjW-U9wnPLYy0ZCsSSrDdbW-B9wifSoX0Axk2xJDs8U-Ptfycf9eMpYDqVAvxX2-JcOkodCfSU9R1BAVkCBwPp4FARAoGQCAMBFEA1LUDStJ0jAAE8SHgABlcgAEEACVyFkeB0IAbnUzTtOMmy7IAESc5yPMoHzzL8qzbIQABRAA5IKPPoSKLP8-FYvgFy4vsuKXIANTioKAH1zA88w0uigKspyvLCuKkq8g8vIqssmq7Lq-KitKtYPLWNqMsChAuoa0qEQ8hFBpizrcu6xrZQ82Vpo6ka5rGkqYw8mMVsy2b6p6kqlw8pdIvUAB6AAqS7rEu+AnPgABhKAIAgAAjKBu106zUCgABbLAwBeiBrPgOAwC7V0OHgACCGQYycEQPaEAASVu+AoFcb7foBoHXtB0AICwV1OHgHoMDhhGkeG+AAHlbvO3z2uRp7gY+7tSBR2hafkGR4AAbycZgykc1zyFoNxnte9nSFp2gUcYGJnRwLBgEimxhd4ELnIl3gUaVlW1aFspEqCiWAH5eEx6yDdVyKAF8zrUK6bqKO6Ho4e4IbJ1AQd0kAiZJ6HgCgDAoAZpmhqy+yveMXnWelz7SGV1XTEYJ2XfRj2AIAax9v3wchkBg9D8O3cZqLmZp+zc4oeOpfepPxfgFPgHTsz0pmhAY96CGADEoEwbTrLrjzmAAOkn2Buw4XgnJgGAoBH63FZxHuYAhuunc71aHNj2mSEXjBtIoWgXPj5gnEn8fp9n+6F6X0gV-UBpmE93uQF4dfN-IVfvG-sg58nYJADCCOYSAYA4D+nFJsGAKDwA0hgN0wBoY5xANZRG8AAAS5AACyAAZOKEAQB-VfDA18uCoAEGRKgHAoBeDkPdOQaeIAMB-n+p-OgXQcAEDmBwS28A3o4BwMQzG8AAA+91gDAEYRgfBWAuBuhADAA+fCX5f1jqQHBBCiEkLIbAyhBAADa5AAC67c1AQUDOAv6VDObc1MAAIRYIgVAohYbwz1g0WmMQ36x14A3GW5BHHyz-vIQJTcQl03TvAMyIDRxQXwLYtB9lkBvQAFbgDgb-ZgMQIkc2br-SK8TIJBngMkkAAB1LsLR7HRNyQEtmScubROKVMUBY4DAASQTAZ0L1mCH1wG4VAyA-pvWUTEABpARljOURY9QyYuACA8hU1JGSsnTNGeMmALBJBmXBJfPElQug2FsQQZgjYcSXLuooE55SqEXOdFcp5ABSeA9BZAyD5uhSQdyznMDejiN649j72QwDAAC3Zcl7OiPsowhybDdOUX0iAzAlLoR+V0f50NvDQzeR8r53zflOH+ayHEAByfwIioDkuJbCyxahFkBRWVANB1SgikC4BC1A3ZaBCJESATGuynZMrBh5A5fgsUPLJd4cwigX5mSAA)). I have created [this](https://github.com/staltz/callbag-map/pull/4) pull request on `callbag-map` (somehow you cannot create issues on that repo?).

I should also note that typing subjects as `Source<T> & Sink<T>` does allow piping, but you would lose type inference ([playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwAcsCQAeAFQEYAaecgJgD4AKRLGAZwwC46b4O4PMF7MovKgEp4AXkZ16kifQCwAKFCRYCFOmx5CxMlVoNTAZhbr4Sdlwk1rAoahHwxD6XIXUnGABbsbh4KXvLk5r5qSnTm6prQcEhomLj4RCQU-GaxpgAsVmo2bJw8fFE2gmDCouJ8YT5+gTDBdQwNERVIOMgwAbUS5h15UTHkefHgiTop+ulGWab0FvmmAKyFxXZlJk5VNe5tlB3LTUEDobLhkU6IPX3+FxHDXWyI-YcSeR1roxJrky0SV0qQMGWM2WWuToIzovzoADZNrZSg4uvtXE9jldGkV4AFzp9Lt5Ord7h8Qs8ceNXlh3o8ieMfuisAAPCltNYdBF-RGA6bJPRpQyZEw+aE0uGmHl0ADsyJK9nKexcrU81NOeIJLSeimpNzxd16HMGL1udJNMOZezZlvIXOpPJVADcQKg7QiOrLeeRZfztILQfNRZCVjD1tLTN66AAOBXbNEq6qYxnYkmamzatXE66vckMylDakjc30p7fam-G3sguc7nokCu921iSe6nepwgLAAcztso6MZ9Mf9wNmwvBi3FnXDUsRUdMg7oAE546jlXiMdmpBqulndR0DcV808iySS4aLS2rZWWTWng6SU6N423R6vV0u72r76B11UFhmyeGMOiXH0lxHGYhTBBYxRyadJXtSM5QXUxQL4AAGVclV2Z9ky3NNwgzfFmi3PUSUPbpjW-U9wnPLYy0ZCsSSrDdbW-B9wifSoX0Axk2xJDs8U-Ptfycf9eMpYDqVAvxX2-JcOkodCfSU9R1BAVkCBwPp4FARAoGQCAMBFEA1LUDStJ0jAAE8SHgABlcgAEEACVyFkeB0IAbnUzTtOMmy7IAESc5yPMoHzzL8qzbIQABRAA5IKPPoSKLP8-FYvgFy4vsuKXIANTioKAH1zA88w0uigKspyvLCuKkq8g8vIqssmq7Lq-KitKtYPLWNqMsChAuoa0qEQ8hFBpizrcu6xrZQ82Vpo6ka5rGkqYw8mMVsy2b6p6kqlw8pdIvUAB6AAqS7rEu+AnPgABhKAIAgAAjKBu106zUCgABbLAwBeiBrPgOAwC7V0OHgACCGQYycEQPaEAASVu+AoFcb7foBoHXtB0AICwV1OHgHoMDhhGkeG+AAHlbvO3z2uRp7gY+7tSBR2hafkGR4AAbycZgykc1zyFoNxnte9nSFp2gUcYGJnRwLBgEimxhd4ELnIl3gUaVlW1aFspEqCiWAH5eEx6yDdVyKAF8zrUK6bqKO6Ho4e4IbJ1AQd0kAiZJ6HgCgDAoAZpmhqy+yveMXnWelz7SGV1XTEYJ2XfRj2AIAax9v3wchkBg9D8O3cZqLmZp+zc4oeOpfepPxfgFPgHTsz0pmhAY96CGADEoEwbTrLrjzmAAOkn2Buw4XgnJgGAoBH63FZxHuYAhuunc71aHNj2mSEXjBtIoWgXPj5gnEn8fp9n+6F6X0gV-UBpmE93uQF4dfN-IVfvG-sg58nYJADCCOYSAYA4D+nFJsGAKDwA0hgN0wBoY5xANZRG8AAAS5AACyAAZOKEAQB-VfDA18uCoAEGRKgHAoBeDkPdOQaeIAMB-n+p-OgXQcAEDmBwS28A3o4BwMQzG8AAA+91gDAEYRgfBWAuBuhADAA+fCX5f1jqQHBBCiEkLIbAyhBAADa5AAC67c1AQUDOAv6VDObcxYIgVAohYbwz1g0WmMQ36xw0R-Tmf95AANluneAZkQGjigvgWxaD7LIDegAK3AHA3+zAYg11QDnUeAAyPefjf6RXCZBIMMN3TKOdC9Zgh9cBuFQMgP6b1lFpM0bU+pyiLHqGTFwAQHlokgFiQkpJpAWkNJgCwSQZlwSXzxJULoNhbEEGYI2HESy7qKFmfAeZiznTLO2QAUngPQWQMg+boUkOszZb0cRvXHsfeyGAYAAW7Kk8Z0R1BAA)). Nevertheless, if you need a typing to at least work for something like this (I did), `Source<T> & Sink<T>` can serve a temporary solution until the typing of `map()` is fixed.

**Comment by staltz** [comment]
For context: https://github.com/cyclejs/callbags/blob/master/src/subject.ts

**Comment by staltz** [comment]
What if the problem is the `void` in the official Callbag types? What if we should use `never` instead?

[playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwAcsCQAeAFQEYAaecgJgD4AKRLGAZwwC46b4O4PMF7MovKgEp4AXkZ16kifQCwAKFCRYCFOmx5CxMlVoNTAZhbr4Sdlwk1rAoahHwxD6XIXUnGABbsbh4KXvLk5r5qSnTm6prQcEhomLj4RCQU-GaxpgAsVmo2bJw8fFE2gmDCouJ8YT5+gTDBdQwNERVIOMgwAbUS5h15UTHkefHgiTop+ulGWab0FvmmAKyFxXZlJk5VNe5tlB3LTUEDobLhkU6IPX3+FxHDXWyI-YcSeR1roxJrky0SV0qQMGWM2WWuToIzovzoADZNrZSg4uvtXE9jldGkV4AFzp9Lt5Ord7h8Qs8ceNXlh3o8ieMfuisAAPCltNYdBF-RGA6bJPRpQyZEw+aE0uGmHl0ADsyJK9nKexcrU81NOeIJLSeimpNzxd16HMGL1udJNMOZezZlvIXOpPJVADcQKg7QiOrLeeRZfztILQfNRZCVjD1tLTN66AAOBXbNEq6qYxnYkmamzatXE66vckMylDakjc30p7fam-G3sguc7nokCu921iSe6nepwgLAAcztso6MZ9Mf9wNmwvBi3FnXDUsRUdMg7oAE546jlXiMdmpBqulndR0DcV808iySS4aLS2rZWWTWng6SU6N423R6vV0u72r76B11UFhmyeGMOiXH0lxHGYhTBBYxRyadJXtSM5QXUxQL4AAGVclV2Z9ky3NNwgzfFmi3PUSUPbpjW-U9wnPLYy0ZCsSSrDdbW-B9wifSoX0Axk2xJDs8U-Ptfycf9eMpYDqVAvxX2-JcOkodCfSU9R1BAVkCBwPp4FARAoGQCAMBFEA1LUDStJ0jAAE8SHgABlcgAEEACVyFkeB0IAbnUzTtOMmy7IAESc5yPMoHzzL8qzbIQABRAA5IKPPoSKLP8-FYvgFy4vsuKXIANTioKAH1zA88w0uigKspyvLCuKkq8g8vIqssmq7Lq-KitKtYPLWNqMsChAuoa0qEQ8hFBpizrcu6xrZQ82Vpo6ka5rGkqYw8mMVsy2b6p6kqlw8pdIvUAB6AAqS7rEu+AnPgABhKAIAgAAjKBu106zUCgABbLAwBeiBrPgOAwC7V0OHgACCGQYycEQPaEAASVu+AoFcb7foBoHXtB0AICwV1OHgHoMDhhGkeG+AAHlbvO3z2uRp7gY+7tSBR2hafkGR4AAbycZgykc1zyFoNxnte9nSFp2gUcYGJnRwLBgEimxhd4ELnIl3gUaVlW1aFspEqCiWAH5eEx6yDdVyKAF8zrUK6bqKO6Ho4e4IbJ1AQd0kAiZJ6HgCgDAoAZpmhqy+yveMXnWelz7SFQF8YFMRgnZd9GPYAgBrH2-fByGQGD0Pw7dxmouZmn7Lzih46l96k-F+AU5JjOzPSmaEBj3oIYAMSgTBtOs+uPOYAA6KfYG7DheCcmAYCgUfrcVnFe5gCH66drvVoc2PaZIJeMG0ihaBc+PmCcKeJ5nuf7sX5fSFX9QGmYT2+5AXgN638g1+8H+ZAL5OwSAGEEcwkAwBwH9OKTYMAUHgBpDAbpgDQ1ziAayiN4AAAlyAAFkAAycUIAgD+q+WBr48FQAIMiVAOBQC8Aoe6cgM8QAYD-P9L+dAug4AIHMDglt4BvRwDgEhmN4AAB97rAGAEwjABCsBcDdCAGAh9+Gv2-rHUguDCHENIeQuBVCCAAG1yAAF0O5qAgoGCBf1qGc25iwRAqBRCw3hnrBotMYjv1jpoz+nN-7yEAbLDO8AzKgNHFBfAdj0H2WQG9AAVuAeBf9mAxEbjLFuf8nbJi4AIDyMSQBxMSck5OyA-pvRUSwSQZlcnGVZB5RAUCYFwOYKgQyEAMbQ2trQdpr0ukY1QDbMyrJmD8D6Z0qA3ShnSHOudFmKioFpwGRZZJIBgBmXBFfPElRaBzPgAAd20rnDgABCJwNg7EEGYI2HEgsdk2EeXMi58B7Y1OiGZIAA)

cc @jvanbruegge

**Comment by loreanvictor** [comment]
> What if the problem is the `void` in the official Callbag types? What if we should use `never` instead?

This was a really interesting suggestion. I played around a bit to fully understand why it works. It is basically because 
```ts
(n: X) => Y
```
is assignable to 
```ts
(n: never) => void
```
but not to 
```ts
(n: void) => void
```
[playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZjAvDAFAQwFwzAVwLYBGApgE4CUSAfDGjRDWAJ4CwAUKJLAGJYphZgiAN1IVE1ISACWAEyTwYAekUwpsKfVAgANmw7QYAcV78Yk2WInS5yBEpVrV9MCFhbdrNspgEcsNNoQIAA0MFwwwGhgLrDEEQHaRDJscCgATBQwWdk5uXl53u5sXOmZ+eUVWd4xESA6xel0DIxlleXVrrX1rCVpTYIi5G3tKkWsQA)

The reason for that is when you want to _cast_ a function of type `(a: A) => B` to type `(c: C) => D`, then `C` needs to be assignable to `A` (you are receiving `C`s and passing them as `A`s to the original function) and `B` to `D` (you are getting `B`s from the original function and returning them as `D`s) ([playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAfQDwEEA0iBC2DC2AIgHwAUAlIgN4CwAUIohAgM5SIBiAXImQIa90VALwlciEYnAATAKbAYYOTMT9WasAE8A3AyYsw7RAHFeZCL3yjxRSVz30AvgyA)). `never` is assignable to all other types (for example `X` in the aforementioned example), but `void` is not.

This also means that with current type definitions, you also have the following undesirable properties (beyond not being able to assign `Callbag<T, T>` to `Source<T>`):
```ts
const s: Source<T> = ...
s(1)                     // --> this is ok, but shouldn't be
s(1, undefined as any)   // --> this is ok, but shouldn't be
```
[playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDKAVAggJQ3AXjgAYBuAWAChRJYFlUARLbQuARguvGniRTgBRAHKM2AJi41e9ATkFpBOAGqDGAfQDMbTVJ51+qeYpVr1AFjbm9tPgzjGlqjQFY2LmzMMOFTswDY2f08De0dTDQB2NkiQuzlfCPUADjZkuNkjROd1AE42XK4qaVCBAGEAQwAbKoAjCoBzAB4ASQAaOAB5AD42AG8qODgAChgALnRsPA6AEwnKmvrmzo6W7oBKCYA3CABLGa4h0YnmbFmJls24Hf3DkfGhUVmAfgmKgDtEK5uDqgBfIrcWyZdAQACuUAAxsAmhhekQFnVGk13sAtsAoB04RlvOo0OCoTC4WxEUsmj8sd0cfY0DAKjAifC4KTkRhKYCZsBIVUKlBUJCIO8AM7wEUTWn0mHvMEAW1qGKpVConO5vNQVWA8HUQomeIJ0JRsvlUEVlG1w3Y6yG1ptNoA9Ha4ABaJ29GAAC12QrgXrgkCFQt2tQ1zqdcHeEHgnMDfJmI2e6yo5vYHXEVtt9sdLrdnu9voj8H9geDqBdcGju1jSaFFtTcAq3o+X2tDtDOd9vqLQZDZYL5eAMeAM2rbBFGdtrezCFzPu9fa7JdD4cj-cHw8oyq5PL5cA1ovF+qlRoVXBrlvH48nrunHbnK4XPbDFarlDPqfTF7gV-bebvhYgAbdqWT4DpWQ5UG+cDiPWjafB+X5ZteHq3su-6AYuZbPuBr6jvAn5DN+N6-n6AHFo+q5gTMQA)

So yes, overall it seems like type definition for `Source<T>` should be changed to `Callbag<never, T>` (and not just for type definition of subjects).

**Comment by staltz** [comment]
#7
